#!/bin/sh

err() {
	echo "$@" >&2
	exit 1
}

if [ "$(id -u)" -ne 0 ]; then
	err 'Please run as root'
fi

if [ -z "$1" ]
then
	err 'Specify path as the first argument'
fi

ensure() {  
	{ set +x; } 2>/dev/null
        [ $# -lt 1 ] && return 0
	$@ || err failed executing: "$@"
	set -x
}

set -xu

umask 022

ensure export chroot_dir="$1"

if [ "$chroot_dir" = "/" ]
then
	err "I don't feel like deleting your root filesystem."
fi

umount "${chroot_dir}/dev"
umount "${chroot_dir}/proc"
umount "${chroot_dir}/sys"

read -p "Really delete ${chroot_dir}? Type 'yes, please!' to confirm: " res
if [ "$res" = "yes, please!" ]
then
	rm -rvf "${chroot_dir}"
else
	err "Not deleting"
fi
